"""chess-game workflow — DataNode-driven full-game evaluation against Stockfish.

Project-local workflow discovered automatically by the factory registry.
Plays full games via a Loop(generator → game_gate) pattern, with GameTask
driving per-instance lifecycle (setup, verify, scoring).
"""

from __future__ import annotations

import sys

from factory.workflow.package import Loop, OptKnob, Package, Port, Sequential
from factory.workflow.primitives import (
    AgentNode,
    AgentRole,
    DataNode,
    GateNode,
    Workflow,
)

from chess_evolve.config import MAX_MOVES
from chess_evolve.pipeline import GAME_TASK_REF

# ── Verbosity instruction mapping ──────────────────────────────
_VERBOSITY_INSTRUCTIONS: dict[str, str] = {
    "uci_only": "Output ONLY the UCI move (e.g. e2e4). Nothing else.",
    "brief_reason": (
        "Output your chosen UCI move on the first line (e.g. e2e4), "
        "then a one-sentence reason on the second line."
    ),
    "detailed": (
        "Output your chosen UCI move on the first line (e.g. e2e4), "
        "then explain your reasoning: key threats, piece activity, "
        "and why alternatives were rejected."
    ),
}


def build_generator_prompt(
    style: str = "balanced",
    verbosity: str = "uci_only",
) -> str:
    """Build the generator prompt interpolating knob values.

    This is called at workflow construction time. When the outer loop
    mutates knobs and rebuilds via WorkflowRegistry, the fresh build
    picks up the new values.

    Args:
        style: Playing style — one of the style knob bounds or an
            expanded value generated by the outer loop.
        verbosity: Output verbosity level — one of 'uci_only',
            'brief_reason', or 'detailed'.

    Returns:
        Formatted prompt string for the generator AgentNode.
    """
    verbosity_instruction = _VERBOSITY_INSTRUCTIONS.get(
        verbosity, _VERBOSITY_INSTRUCTIONS["uci_only"]
    )
    return (
        f"You are playing chess with a {style} style. "
        f"Look at the board position and legal moves. "
        f"Pick a move. {verbosity_instruction}"
    )


meta = {
    "name": "chess-game",
    "description": "DataNode-driven full-game evaluation against Stockfish",
}


def workflow() -> Workflow:
    """Build a DataNode-driven workflow for full-game evaluation.

    Structure::

        DataNode(games)
          └─ subgraph: Loop(generator → game_gate, max_iterations=MAX_MOVES)
               ├─ generator: AgentNode(reads board_state + memory, writes move)
               └─ game_gate: GateNode(advance_game_state → RELOOP | PROCEED)

    Returns:
        Workflow with DataNode 'games' as start node wrapping the game loop.
    """
    # ── 1. Knob definitions ────────────────────────────────────
    style_knob = OptKnob(
        name="style",
        kind="prompt",
        node_id="generator",
        default="balanced",
        bounds=["balanced", "tactical", "positional", "aggressive"],
        expandable=True,
        expansion_hint=(
            "Generate a chess playing style that the LLM should adopt "
            "when selecting moves"
        ),
        description="High-level playing style guiding move selection",
    )

    verbosity_knob = OptKnob(
        name="verbosity",
        kind="prompt",
        node_id="generator",
        default="uci_only",
        bounds=["uci_only", "brief_reason", "detailed"],
        expandable=False,
        description="Controls how much reasoning the generator outputs with the move",
    )

    # ── 2. Generator AgentNode ──────────────────────────────────
    generator = AgentNode(
        id="generator",
        role=AgentRole.STRATEGIST,
        prompt_template=build_generator_prompt(
            style=style_knob.default,
            verbosity=verbosity_knob.default,
        ),
        reads={".factory/chess/board_state.md", ".factory/chess/memory.md"},
        writes={".factory/chess/move.md"},
    )

    # ── 3. Game gate GateNode ───────────────────────────────────
    game_gate = GateNode(
        id="game_gate",
        evaluator_type="fn",
        evaluator_command=(
            f"{sys.executable} {{project_path}}/.factory/workflows/chess_game_gate.py"
            ' "{project_path}"'
        ),
    )

    # ── 4. Package the generator for Loop composition ───────────
    generator_pkg = Package(
        name="move-generator",
        inputs=[Port(name="board", artifact_path=".factory/chess/board_state.md")],
        outputs=[Port(name="move", artifact_path=".factory/chess/move.md")],
        graph=Workflow(
            name="move-gen",
            nodes={"generator": generator},
            edges=[],
            start_node="generator",
        ),
        entry_node="generator",
        exit_node="generator",
        knobs=[style_knob, verbosity_knob],
    )

    # ── 5. Loop: generator → game_gate ──────────────────────────
    game_body = Sequential(generator_pkg, name="generate-move")
    game_loop = Loop(
        game_body,
        game_gate,
        max_iterations=MAX_MOVES,
        name="game-loop",
    )

    # ── 6. Compile loop into flat workflow ───────────────────────
    loop_wf = game_loop.compile()

    # ── 7. DataNode wraps the compiled loop subgraph ────────────
    data_node = DataNode(
        id="games",
        task_ref=GAME_TASK_REF,
        subgraph_entry=loop_wf.start_node,
        subgraph_exit="exit_game-loop",
        parallelism=1,
        writes={".factory/chess/game_results.json"},
    )

    # ── 8. Assemble final workflow ──────────────────────────────
    all_nodes: dict = {"games": data_node, **loop_wf.nodes}
    return Workflow(
        name="chess-game",
        nodes=all_nodes,
        edges=loop_wf.edges,
        start_node="games",
        knob_values=loop_wf.knob_values,
        knob_bounds=loop_wf.knob_bounds,
        knob_expandable=loop_wf.knob_expandable,
    )
